# Generated by Django 6.0.2 on 2026-02-26 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(default=2023, verbose_name='Рік')),
                ('car_class', models.CharField(choices=[('economy', 'Економ'), ('comfort', 'Комфорт'), ('business', 'Бізнес'), ('vip', 'VIP'), ('crossover', 'Кросовер'), ('minivan', 'Мінівен'), ('electric', 'Електро')], default='comfort', max_length=20, verbose_name='Клас')),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид')], default='petrol', max_length=20, verbose_name='Паливо')),
                ('transmission', models.CharField(default='Автомат', max_length=30, verbose_name='КПП')),
                ('seats', models.IntegerField(default=5, verbose_name='Місць')),
                ('engine', models.CharField(blank=True, max_length=40, verbose_name='Двигун')),
                ('drive', models.CharField(default='Передній', max_length=20, verbose_name='Привід')),
                ('color', models.CharField(default='Чорний', max_length=30, verbose_name='Колір')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Держ. номер')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробіг км')),
                ('price_base', models.DecimalField(decimal_places=2, default=50, max_digits=8, verbose_name='Base USD/доба')),
                ('price_prime', models.DecimalField(decimal_places=2, default=70, max_digits=8, verbose_name='Prime USD/доба')),
                ('deposit', models.DecimalField(decimal_places=2, default=1500, max_digits=8, verbose_name='Застава USD')),
                ('status', models.CharField(choices=[('free', 'Вільний'), ('rented', 'У прокаті'), ('service', 'На ТО'), ('broken', 'Несправний')], default='free', max_length=20, verbose_name='Статус')),
                ('next_service', models.DateField(blank=True, null=True, verbose_name='Наступне ТО')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('features', models.TextField(blank=True, verbose_name='Особливості (через кому)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('emoji', models.CharField(default='🚗', max_length=8, verbose_name='Емодзі')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На головній')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['car_class', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер')),
                ('date_from', models.DateField(verbose_name='Від')),
                ('date_to', models.DateField(verbose_name='До')),
                ('time_from', models.TimeField(default='10:00', verbose_name='Час')),
                ('pickup_location', models.CharField(choices=[('office', 'Офіс, вул. Клочківська, 94а'), ('airport', 'Аеропорт «Харків»'), ('station', 'Залізничний вокзал'), ('delivery', 'Доставка по місту')], default='office', max_length=10, verbose_name='Місце')),
                ('tariff', models.CharField(choices=[('base', 'Base (зі заставою)'), ('prime', 'Prime (без застави)')], default='base', max_length=10, verbose_name='Тариф')),
                ('payment_method', models.CharField(choices=[('card', 'Картка'), ('cash', 'Готівка'), ('bank', 'Безготівковий')], default='card', max_length=10, verbose_name='Оплата')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('active', 'Активне'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('extra_gps', models.BooleanField(default=False, verbose_name='GPS')),
                ('extra_child_seat', models.BooleanField(default=False, verbose_name='Дитяче крісло')),
                ('extra_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('extra_driver', models.BooleanField(default=False, verbose_name='Доп. водій')),
                ('extra_tire', models.BooleanField(default=False, verbose_name='Захист шин')),
                ('extra_green_card', models.BooleanField(default=False, verbose_name='Зелена картка')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума USD')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Застава USD')),
                ('manager_note', models.TextField(blank=True, verbose_name='Нотатка')),
                ('promo_code', models.CharField(blank=True, max_length=50, verbose_name='Промокод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.car')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адреса')),
                ('driver_license', models.CharField(blank=True, max_length=20, verbose_name='ВП')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Стаж (років)')),
                ('segment', models.CharField(choices=[('new', 'Новий'), ('regular', 'Постійний'), ('vip', 'VIP'), ('blocked', 'Заблокований')], default='new', max_length=10, verbose_name='Сегмент')),
                ('discount_pct', models.IntegerField(default=0, verbose_name='Знижка %')),
                ('manager_note', models.TextField(blank=True, verbose_name='Нотатка менеджера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер')),
                ('fine_type', models.CharField(choices=[('late_return', 'Запізнення повернення'), ('body_damage', 'Пошкодження кузову'), ('interior_damage', 'Пошкодження салону'), ('empty_tank', 'Неповний бак'), ('accident', 'ДТП'), ('traffic_fine', 'Штраф ДАІ'), ('other', 'Інше')], default='other', max_length=30, verbose_name='Тип')),
                ('severity', models.CharField(choices=[('low', 'Мінімальна'), ('medium', 'Середня'), ('high', 'Критична')], default='medium', max_length=10, verbose_name='Серйозність')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума USD')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сплачено USD')),
                ('status', models.CharField(choices=[('unpaid', 'Непогашений'), ('paid', 'Сплачений'), ('partial', 'Часткова'), ('disputed', 'Оскаржується'), ('waived', 'Скасований')], default='unpaid', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fines/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='core.booking')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=30, unique=True, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('rental', 'Оренда'), ('deposit', 'Застава'), ('fine', 'Штраф'), ('refund', 'Повернення')], default='rental', max_length=10, verbose_name='Тип')),
                ('method', models.CharField(choices=[('card', 'Картка'), ('cash', 'Готівка'), ('bank', 'Безготівковий')], default='card', max_length=10, verbose_name='Метод')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума USD')),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('pending', 'Очікує'), ('failed', 'Відхилено'), ('refund', 'Повернення'), ('deposit_held', 'Застава утримується'), ('deposit_released', 'Застава звільнена')], default='success', max_length=20, verbose_name='Статус')),
                ('bank_ref', models.CharField(blank=True, max_length=50, verbose_name='Банк. ID')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.booking')),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.fine')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='core.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'car')},
            },
        ),
    ]
