# Generated by Django 6.0.2 on 2026-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса повернення'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_location',
            field=models.CharField(choices=[('office', 'Офіс, вул. Клочківська, 94а'), ('airport', 'Аеропорт «Харків»'), ('station', 'Залізничний вокзал'), ('delivery', 'Доставка по місту'), ('delivery_out', 'Доставка за місто')], default='office', max_length=20, verbose_name='Місце повернення'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_to',
            field=models.TimeField(default='10:00', verbose_name='Час повернення'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорту'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ідентифікаційний код'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(choices=[('office', 'Офіс, вул. Клочківська, 94а'), ('airport', 'Аеропорт «Харків»'), ('station', 'Залізничний вокзал'), ('delivery', 'Доставка по місту'), ('delivery_out', 'Доставка за місто')], default='office', max_length=20, verbose_name='Місце отримання'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_from',
            field=models.TimeField(default='10:00', verbose_name='Час отримання'),
        ),
    ]